name: CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Cache SonarQube Scanner
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: sonar-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          sonar-${{ runner.os }}-
    - name: Build with Maven
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -Pci -B verify sonar:sonar